---
apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "reporting-redis-db-statefulset"
  labels:
    app.kubernetes.io/name: "surveysystem-apphost"
    app.kubernetes.io/component: "reporting-redis-db"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "surveysystem-apphost"
        app.kubernetes.io/component: "reporting-redis-db"
        app.kubernetes.io/instance: "{{.Release.Name}}"
    spec:
      containers:
        - image: "docker.io/library/redis:8.2"
          name: "reporting-redis-db"
          envFrom:
            - secretRef:
                name: "reporting-redis-db-secrets"
          args:
            - "redis-server"
            - "--requirepass"
            - "$REDIS_PASSWORD"
          ports:
            - name: "tcp"
              protocol: "TCP"
              containerPort: 6379
          imagePullPolicy: "IfNotPresent"
  selector:
    matchLabels:
      app.kubernetes.io/name: "surveysystem-apphost"
      app.kubernetes.io/component: "reporting-redis-db"
      app.kubernetes.io/instance: "{{.Release.Name}}"
  replicas: 1
  persistentVolumeClaimRetentionPolicy: {}
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 0
    type: "RollingUpdate"
